# FROM maven:3.9.4-eclipse-temurin-17 AS build-starter
# RUN apt-get update && apt-get install -y git
# RUN git clone https://github.com/Boraldan/T1-Learning-Starter.git /build/starter
# WORKDIR /build/starter
# RUN mvn -f pom.xml clean install -DskipTests -e
#
# FROM maven:3.9.4-eclipse-temurin-17 AS build
# WORKDIR /build
# COPY --from=build-starter /build/starter/target/starter-0.0.1-SNAPSHOT.jar /root/.m2/repository/ru/boraldan/log-aspect-starter/starter/0.0.1-SNAPSHOT/starter-0.0.1-SNAPSHOT.jar
# COPY task-aop/pom.xml ./task/
# COPY task-aop/src ./task/src
# WORKDIR /build/task
# RUN mvn clean package -DskipTests
#
# FROM openjdk:17
# WORKDIR /app
# RUN mkdir -p logs
# COPY --from=build /build/task/target/*-SNAPSHOT.jar /app/app.jar
# ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# -----------------------------

FROM maven:3.9.4-eclipse-temurin-17 AS build-entity
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/Boraldan/T1-Learning-Starters.git /build/entity
WORKDIR /build/entity/entity-dto-repo
RUN mvn clean install -DskipTests
RUN mvn install:install-file \
  -Dfile=target/entity-dto-repo-1.0-SNAPSHOT.jar \
  -DgroupId=ru.boraldan.task-starters \
  -DartifactId=entity-dto-repo \
  -Dversion=1.0-SNAPSHOT \
  -Dpackaging=jar

FROM maven:3.9.4-eclipse-temurin-17 AS build-starter
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/Boraldan/T1-Learning-Starters.git /build/starter
COPY --from=build-entity /root/.m2 /root/.m2
WORKDIR /build/starter/kafka-starter
RUN mvn clean install -DskipTests
WORKDIR /build/starter/log-aop-starter
RUN mvn clean install -DskipTests

FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /build
COPY --from=build-entity /build/entity/entity-dto-repo/target/entity-dto-repo-1.0-SNAPSHOT.jar /root/.m2/repository/ru/boraldan/task-starters/entity-dto-repo/1.0-SNAPSHOT/
COPY --from=build-starter /build/starter/kafka-starter/target/kafka-starter-0.0.1-SNAPSHOT.jar /root/.m2/repository/ru/boraldan/task-starters/kafka-starter/0.0.1-SNAPSHOT/
COPY --from=build-starter /build/starter/log-aop-starter/target/log-aop-starter-0.0.1-SNAPSHOT.jar /root/.m2/repository/ru/boraldan/task-starters/log-aop-starter/0.0.1-SNAPSHOT/

COPY task-aop/pom.xml ./task/
COPY task-aop/src ./task/src
WORKDIR /build/task
RUN mvn clean package -DskipTests

FROM openjdk:17
WORKDIR /app
RUN mkdir -p logs
COPY --from=build /build/task/target/*-SNAPSHOT.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

