kafka:
#  bootstrap-servers: "kafka1:9092"
  bootstrap-servers: "localhost:9092"
  max-pull-interval: "100000"
  consumer:
    tasks-update-status:
      topic: tasks-update-status-topic
      group-id: tasks-update-status-group
      container-factory: tasksDtoListenerContainerFactory
      auto-offset-reset: earliest
      payload-dto: ru.boraldan.aop.taskaop.domen.dto.TasksDto

  producer:
    tasks-update-status-topic:

