postgres:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123

mail:
  host: smtp.gmail.com
  port: 587
  username: born17121982@gmail.com
  password: ltpuiznhkjmssety
  email-recipient: boraldan@gmail.com

